name: CI workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
  defaults:
      run:
        working-directory: app
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: npm install
      - name: Build the project
        run: npm run build --if-present
      - name: Run tests
        run: npm test
      - name: Run code style check
        run: npm run style:all
